using System;
namespace ITSNet.Common.BIZ
{
	public enum OrderMessageType
	{
		NewOrder,
		CancelOrder,
		OrderConfirmation,
		ConfirmationCancel,
		DealConfirmation,
		Reject,
		CrossingDealConfirm,
		Approve,
		DisApprove,
		ExerciseOrder,
		ChangeOrder,
		ConfirmOrderChange,
		EditOrder,
		PuttDealConfirm,
		PuttDealAcknowledgment,
		PuttDealReply,
		PuttDealCancelRequest,
		PuttDealCancelReply,
		PuttSendApprove,
		PuttSendCancelRequest,
		PuttSendApproveCancel,
		PuttSendNewOrder,
		AutoServiceCreateNewOrder,
		AutoServiceCreateCancelOrder,
		OrderAfterClose,
		SETMkt,
		PositionReport,
		DepositBalanceRequest,
		DepositBalanceReport,
		PositionRequest,
		OrderMassStatusRequest,
		TradeCaptureRequest,
		TradeCaptureReport
	}
}
